[package]
name = "battery_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }

[dev-dependencies]
approx = "0.6.0-rc1"
